baseurl = "https://andrewrgoss.com/"
languageCode = "en-us"
title = "Andrew Goss Â· Staff Data Engineer"
paginate = 7
theme = "crisp"
pluralizelisttitles = false
googleAnalytics = "UA-58296426-1"
disqusShortname = "andrewrgoss"

[params]
    twitter = "Andrewrgoss"
    description = "Andrew Goss is a staff data engineer based in the Boston, MA area. He builds performant backend systems that integrate disparate data sources and empower end users to uncover key insights that tell a bigger story."
    email = "admin@andrewrgoss.com"
    hostname = "https://andrewrgoss.github.io"

[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[author]
    name = "Andrew Goss"
    twitter = "Andrewrgoss"
    email = "admin@andrewrgoss.com"

[taxonomies]
    tag = "tags"